apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::883656809667:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-KXBAX4EVRD9Z
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::883656809667:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T13:16:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1479"
  uid: dba41275-da77-4de4-bfb9-6c43b4966042
